spring.application.name=outdoor-activity
spring.profiles.active=local

# Server
server.port=8080

#SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Actuator: expose health and info endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized

#Latitude and longitude for notification (Currently: Plovdiv)
notification.latitude=42.1
notification.longitude=24.7

# How often the watcher checks the forecast(ms).
notification.check-interval-ms=21600000